[package]
name = "prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
encase = "0.9.0"
env_logger = "0.11.5"
image = "0.25.2"
mlua = { version = "0.9.9", features = ["lua54"] }
pollster = "0.3.0"
wgpu = "22.1.0"
