[package]
name = "prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
env_logger = "0.11.5"
flume = "0.11.0"
image = "0.25.2"
pollster = "0.3.0"
wgpu = "22.1.0"
